name: @name@
main: @mainPackage@
version: @version@
depend:
  - TimerAPI
  - WorldEdit
commands:
  shuffle:
    permission: annihilation.command.shuffle
permissions:
  annihilation.command.*:
    children:
      annihilation.command.shuffle: true
  annihilation.command.shuffle:
    default: op