name: @name@
main: @mainPackage@
version: @version@
depend:
  - TimerAPI
  - WorldEdit
  - Citizens
commands:
  shuffle:
    permission: annihilation.command.shuffle
  setmap:
    permission: annihilation.command.setmap
  anni-start:
    permission: annihilation.command.anni-start
  mapconfig:
    permission: annihilation.command.mapconfig
  kill:
    permission: annihilation.command.kill
permissions:
  annihilation.command.*:
    children:
      annihilation.command.shuffle: true
      annihilation.command.setmap: true
      annihilation.command.anni-start: true
      annihilation.command.mapconfig: true
      annihilation.command.kill: true
  annihilation.command.shuffle:
    default: op
  annihilation.command.setmap:
    default: op
  annihilation.command.anni-start:
    default: op
  annihilation.command.mapconfig:
    default: op
  annihilation.command.kill:
    default: true